\ GCD - GREATEST COMMON DIVISOR
: GCD ( A B -- GCD )
   OVER IF
      BEGIN
	 DUP WHILE
	    2DUP > IF SWAP THEN OVER -
      REPEAT DROP ELSE
      DUP IF NIP ELSE 2DROP 1 THEN
   THEN ;

: GCD1-BENCH 1000 0 DO
      1000 0 DO J I GCD DROP LOOP
   LOOP ;

GCD1-BENCH
