name: Non regression tests for SimForth
on:
  workflow_dispatch:
    branches:
      - master
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  non_regression_linux:
    name: Non regression tests on Linux
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install pkg-config lcov libdw-dev bc libreadline-dev libgtksourceviewmm-3.0-dev
      - name: Download, configure and install Google test
        run: |
          wget https://github.com/google/googletest/archive/release-1.11.0.tar.gz
          tar xf release-1.11.0.tar.gz
          cd googletest-release-1.11.0
          cmake -DBUILD_SHARED_LIBS=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON .
          sudo make install
      - name: Compile SimForth
        run: |
          make download-external-libs
          make -j`nproc --all`
          sudo make install
      - name: Do non regression tests
        run: |
          cd tests
          make -j`nproc --all`
          ./build/SimForth-UnitTest
      - name: Compile Forth IDE
        run: |
          cd src/editor
          make -j`nproc --all`
      - name: Compile spreadsheet demo
        run: |
          cd src/spreadsheet
          make -j`nproc --all`
      - name: Check if the library can be linked against a project
        run: |
          git clone https://github.com/Lecrapouille/LinkAgainstMyLibs.git --recurse-submodules --depth=1
          cd LinkAgainstMyLibs/Forth
          make -j`nproc --all`
          cd ../ExtendedForth
          make -j`nproc --all`

  non_regression_macos:
    name: Non regression tests on MacOS X
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Install packages
        run: |
          brew install pkg-config
      - name: Download, configure and install Google test
        run: |
          wget https://github.com/google/googletest/archive/release-1.11.0.tar.gz
          tar xf release-1.11.0.tar.gz
          cd googletest-release-1.11.0
          cmake -DBUILD_SHARED_LIBS=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON .
          sudo make install
      - name: Compile SimForth
        run: |
          make download-external-libs
          make -j`sysctl -n hw.logicalcpu`
# FIXME: Failed reading in 'System/Core.fth'. Reason 'No such file or directory'
#      - name: Do non regression tests
#        run: |
#          cd tests
#          make -j`sysctl -n hw.logicalcpu`
#          ./build/SimForth-UnitTest

#      - name: Compile Forth IDE
#        run: |
#          cd src/editor
#          make -j`nproc --all`
#      - name: Compile spreadsheet demo
#        run: |
#          cd src/spreadsheet
#          make -j`nproc --all`

#      - name: Check if the library can be linked against a project
#        run: |
#          git clone https://github.com/Lecrapouille/LinkAgainstMyLibs.git --recurse-submodules --depth=1
#          cd LinkAgainstMyLibs/Forth
#          make -j`nproc --all`
#          cd ../ExtendedForth
#          make -j`nproc --all`
